version: 2
updates:
    - package-ecosystem: "docker"
      directory: /
      schedule:
          interval: "daily"
          timezone: "America/Sao_Paulo"
          time: "05:00"
    - package-ecosystem: "github-actions"
      directory: /
      schedule:
          interval: "daily"
          timezone: "America/Sao_Paulo"
          time: "05:00"
