version: '3'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.5
    environment:
      MEILI_ENV: development
      MEILI_NO_ANALYTICS: false
      MEILI_MASTER_KEY: key_meili
    volumes:
      - "./data/melisearch/dev:/data.ms"
    ports:
      - 7700:7700
